### ISSUE TITLE
feat: Disable vibration

### ISSUE THREAD

**Issue by xmrv** [tsinis/colors_ai#125]

**Comment by tsinis** [comment]
Hey @xmrv!

Thanks for your interest, should I consider your message as a feature request? If so, I can add a simple switch to the settings menu next week and release it in version 2.2.1. WDYT?

**Comment by xmrv** [comment]
That would be lovely, thank you :)

**Comment by tsinis** [comment]
@xmrv 2.2.1 is on review on both Microsoft Store and Google Play Store and should go online in about 12-24h. Otherwise downloadable binaries are in the [Release section](https://github.com/tsinis/colors_ai/releases). If you will need some other features or bug fixes, just let me know. Thanks for starring a repo!
