### ISSUE TITLE
Wrong default locale

### ISSUE THREAD

**Issue by TaylanTatli** [tsinis/colors_ai#5]
Hi! I installed app but it starts with a wrong locale (it's Czech i guess). My phone locale is Turkish, I was expecting English. I couldn't find a settings to change it.![Screenshot_20220103-082827.jpg](https://user-images.githubusercontent.com/754514/147901872-6c66d998-e1b4-495e-864b-61008a8994ed.jpg)

**Comment by tsinis** [comment]
Hey @TaylanTatli 

Thanks for reporting the issue. I've received such reports also from other users after updating the app from 1.5 to 2.0. Can you please try to do a clean app uninstall and reinstall? It might fix the issue. Please let me know.

P.S. I don't manage app detection manually, it's done by Flutter, so it might be a bug of framework :(

**Comment by TaylanTatli** [comment]
Hi. I tried uninstalling and reinstalling but unfortunately didn't work. :confused:

**Comment by tsinis** [comment]
@TaylanTatli I see the issue and can replicate it, I'll publish hot-fix today, so expect it in a few days on Google Play Store or today/tomorrow in the Release section.

**Comment by TaylanTatli** [comment]
Cool. Thank you.

**Comment by tsinis** [comment]
> Cool. Thank you.

So it's on Play Store review (it usually takes several hours to a few days to rollout). I'm about to publish binaries to the Release section in a few hours. Thanks for your report, I appreciate it a lot! Please let me know if it was fixed in this update.

<img width="1186" alt="Screenshot 2022-01-08 at 17 49 46" src="https://user-images.githubusercontent.com/52065414/148652574-c35728cb-38cc-46b1-b70b-c18aae739cae.png">

**Comment by TaylanTatli** [comment]
Installed from Google Play. It's working. Thank you. 👍🏼

**Comment by arkonny** [comment]
Hello, the same problem appears on linux, via snapcraft on ubuntu 20.04.3
I have my OS in french, but having the app in english is good as well if there is no translation in french.
![image](https://user-images.githubusercontent.com/81641732/151526037-69e1f6a1-8291-49cd-aa73-fe5e18a76309.png)

**Comment by tsinis** [comment]
> Hello, the same problem appears on linux, via snapcraft on ubuntu 20.04.3 I have my OS in french, but having the app in english is good as well if there is no translation in french. ![image](https://user-images.githubusercontent.com/81641732/151526037-69e1f6a1-8291-49cd-aa73-fe5e18a76309.png)

Hey @arkonny 

Sadly Snapcraft's Flutter CMake version is very outdated, so I cannot publish the version with a fix in SnapStore at this moment (since version 2.0.0 there are two libs that require CMake version 15+). There is an open draft PR (from December 6) that will allow us to use core20 for building :(. You can grab the Linux version from the Releases section, but I'd suggest you wait for a while till core20 become available for snaps.
